# Dockerfile.importer
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Копируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код
COPY . .

# Компилируем импортер
RUN CGO_ENABLED=0 GOOS=linux go build -o importer ./cmd/import

# Финальный образ
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /root/

COPY --from=builder /app/importer .

# Делаем исполняемым
RUN chmod +x ./importer

ENTRYPOINT ["./importer"]